# Generated by Django 3.1.1 on 2020-09-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descp', models.CharField(max_length=200)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TodoAPI.list')),
            ],
        ),
    ]
